### PR TITLE
Fix and tidy tests

### LINKED ISSUE #415: xios test fails for gfortran build
the `testXiosInit ` test currently fails.

```
build/core/test$ XIOS_IODEF_PATH=/.../nextsimdg/run mpirun -np 1 ./testXiosInit 
1
INIT CONFIGURE ENTRY
In file "calendar.cpp", function "void xios::CCalendar::setTimeStep(const xios::CDuration&)",  line 117 -> Circular definition of the timestep: the timestep cannot refer to itself.

CONFIGURE CALENDAR P0-0T1:0:0 2023-03-03 17:11:00 1970-01-01 00:00:00
SET TIMESTEP 
(1) **************** void cxios_update_calendar_timestep(XCalendarWrapperPtr)

      File                                    Function                                                                                                  Line 
(1)   iccalendar_wrapper.cpp                  void cxios_update_calendar_timestep(XCalendarWrapperPtr)                                                  139  
terminate called after throwing an instance of 'xios::CException'
[lenny:188155] *** Process received signal ***
[lenny:188155] Signal: Aborted (6)
[lenny:188155] Signal code:  (-6)
[lenny:188155] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x42520)[0x7f3a061d6520]
[lenny:188155] [ 1] /lib/x86_64-linux-gnu/libc.so.6(pthread_kill+0x12c)[0x7f3a0622aa7c]
[lenny:188155] [ 2] /lib/x86_64-linux-gnu/libc.so.6(raise+0x16)[0x7f3a061d6476]
[lenny:188155] [ 3] /lib/x86_64-linux-gnu/libc.so.6(abort+0xd3)[0x7f3a061bc7f3]
[lenny:188155] [ 4] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xa2b9e)[0x7f3a06565b9e]
[lenny:188155] [ 5] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae20c)[0x7f3a0657120c]
[lenny:188155] [ 6] /lib/x86_64-linux-gnu/libstdc++.so.6(+0xae277)[0x7f3a06571277]
[lenny:188155] [ 7] /lib/x86_64-linux-gnu/libstdc++.so.6(__cxa_rethrow+0x4b)[0x7f3a0657152b]
[lenny:188155] [ 8] ./testXiosInit(+0x1ca0da)[0x55f5cbaea0da]
[lenny:188155] [ 9] ./testXiosInit(+0x1a18a5)[0x55f5cbac18a5]
[lenny:188155] [10] ./testXiosInit(+0x1a118c)[0x55f5cbac118c]
[lenny:188155] [11] ./testXiosInit(+0x1a0b21)[0x55f5cbac0b21]
[lenny:188155] [12] ./testXiosInit(+0x187756)[0x55f5cbaa7756]
[lenny:188155] [13] /lib/x86_64-linux-gnu/libc.so.6(+0x29d90)[0x7f3a061bdd90]
[lenny:188155] [14] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0x80)[0x7f3a061bde40]
[lenny:188155] [15] ./testXiosInit(+0x171c35)[0x55f5cba91c35]
[lenny:188155] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 0 on node lenny exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

### PR DESCRIPTION
**Pull request by TomMelt**
# fix and tidy XIOS tests
## Fixes #415

The `testXiosInit` test was failing to run when compiled with `gnu` compiler. It worked for `intel` compiler and my suspicion is that `intel` compilers will often initialize uninitialized variables to zero. This is not the case for `gcc`. This meant that `dduration.timestep` was not being properly set and it led to the bug in #415.

This has been resolved and I have also tidied the test cases.

### CODE REVIEW

File: core/src/Xios.cpp [hunk 1]
```diff
@@ -363,9 +363,7 @@ cxios_duration Xios::convertStringToXiosDuration(std::string timestep_str)
         }
     }
 
-    // std::cout << "Duration Year: " << dduration.year << std::endl;
-    // std::cout << "Duration Month: " << dduration.month << std::endl;
-    // std::cout << "Duration Day: " << dduration.day << std::endl;
+    dduration.timestep = 0;
```
Comment (TomMelt) [inline core/src/Xios.cpp:366]: This is the main fix. The rest of the changes just tidy up the test classes.
