### PR TITLE
Wrap XIOS frequency splitting and fix timestep bug

### LINKED ISSUE #554: Support XIOS' frequency splitting option
The `split_freq` attribute of XIOS' file class allows separate output files to be created for different time intervals, as defined by a frequency (e.g., every 2 simulated days).

### PR DESCRIPTION
**Pull request by jwallwork23**
# Wrap XIOS frequency splitting and fix timestep bug
### Task List
- [x] Defined the tests that specify a complete and functioning change (*It may help to create a [design specification & test specification](../../../wiki/Specification-Template)*)
- [x] Implemented the source code change that satisfies the tests
- [x] Documented the feature by providing worked example
- [x] Updated the README or other documentation
- [x] Completed the pre-Request checklist below

---
# Change Description

Closes #554. Wraps the `split_freq` option for XIOS Files, so that output files can be separated according to some frequency.

While working on this, I spotted a bug: the timestep is interpreted as minutes rather than seconds. This is now fixed.

---
# Test Description

A test for the frequency splitting option is added, which checks a frequency of 2 timesteps works.

Another test is added to verify that the timestep is set up correctly.

---
### Pre-Request Checklist

- [x] The requirements of this pull request are fully captured in an issue or design specification and are linked and summarised in the description of this PR
- [x] No new warnings are generated
- [x] The documentation has been updated (or an issue has been created to track the corresponding change)
- [x] Methods and Tests are commented such that they can be understood without having to obtain additional context
- [x] This PR/Issue is labelled as a bug/feature/enhancement/breaking change
- [x] File dates have been updated to reflect modification date
- [x] This change conforms to the conventions described in the README

### CODE REVIEW

File: core/test/XiosFile_test.cpp [hunk 1]
```diff
@@ -83,6 +83,10 @@ MPI_TEST_CASE("TestXiosFile", 2)
     xios_handler.setFileOutputFreq(fileId, freq);
     REQUIRE(xios_handler.isDefinedFileOutputFreq(fileId));
     REQUIRE(xios_handler.getFileOutputFreq(fileId) == freq);
+    // Split frequency
+    const std::string splitFreq { "1ts" };
```
Comment (timspainNERSC) [inline core/test/XiosFile_test.cpp:87]: Is this a typical way of setting a std::string? I can see that it works, and how, but I would always use
```
const std::string splitFreq = "1ts";
```
I'd suggest we stick to one or the other in the code base. If the `{}` version is currently preferred, then I'll switch all my `const std::string`s over as I touch their files.

**Review by timspainNERSC — CHANGES_REQUESTED** [review]
Could you take a look at the `const std::string` assignment? Otherwise, this all looks reasonable.

File: core/test/XiosFile_test.cpp (hunk 1 above)
Comment (jwallwork23) [reply core/test/XiosFile_test.cpp:87]: Oh good point. In other tests I followed Tom's approach elsewhere, which read like
```
std::string splitFreq = { "1ts"};
```
I'd meant to use the same notation but must have reverted to this instead.

While we're on the topic, though, the C++ course I did recently did recommend initialising variables with
```
std::string splitFreq { "1ts"};
```
rather than
```
std::string splitFreq = "1ts";
```
There are some reasons behind this listed here: https://stackoverflow.com/questions/18222926/what-are-the-advantages-of-list-initialization-using-curly-braces. (TLDR: _Prefer {} initialization over alternatives unless you have a strong reason not to._)

**Review by timspainNERSC — APPROVED** [review]

File: core/test/XiosFile_test.cpp (hunk 1 above)
Comment (timspainNERSC) [reply core/test/XiosFile_test.cpp:87]: Excellent, thank you :)
